// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iihxdmrioehokrlwdyxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpaHhkbXJpb2Vob2tybHdkeXhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1OTM2MjksImV4cCI6MjA2MDE2OTYyOX0.Jsu-Mkd5V1ejPLZAPmcRmHfo74GwX_FAzhujQfW2Xp0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);